### ISSUE TITLE
Fatal error when moving "vendor-dir"

### ISSUE THREAD

**Issue by scottatdrake** [cweagans/composer-patches#263]
I'd like to move /vendor to /web/vendor so that it ends up in the deployed package, but when I try to do so using the the `"vendor-dir": "web/vendor"` config option, I get the following fatal error. Are there any adjustments that could be made to our project's composer.json to allow the patching to complete? 

```
PHP Fatal error:  Uncaught Error: Class 'cweagans\Composer\PatchEvent' not found in /Users/******/Sites/ddev/web/vendor/cweagans/composer-patches/src/Patches.php:312
Stack trace:
#0 [internal function]: cweagans\Composer\Patches->postInstall(Object(Composer\Installer\PackageEvent))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Installer\PackageEvent))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(116): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Installer\PackageEvent))
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(609): Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent('post-package-in...', true, Object(Composer\DependencyResolver\DefaultPolicy), Object(Composer\DependencyResolver\Pool), Object(Composer\Repository\CompositeRepository), Object(Composer\DependencyResolver\Request), Array, Object(Composer\DependencyResolver\Operation\InstallOperation))
#4 ph in /Users/sphillips/Sites/ddev/web/vendor/cweagans/composer-patches/src/Patches.php on line 312
```

**Comment by cweagans** [comment]
You could set the vendor dir back to it's default value ;) 

I'm actually not sure why this is happening. It seems like more of an issue with the Composer autoloader tbh.

**Comment by scottatdrake** [comment]
Yeah, this seems to be the result of some combination of factors in our process. Thanks.
